### ISSUE TITLE
What is the StArMap service?

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/starmap-client#5]
Readme references the "StArMap service" - what is this?

**Comment by JAVGan** [comment]
It's an internal service to map VM builds to the cloud marketplaces destinations

**Comment by JAVGan** [comment]
We've added a more descriptive phrase on README, please let us know if it's good to you now

**Comment by lslebodn** [comment]
A month should be enough to provide feedback after changing REDME.
=> c losing

**Comment by ktdreyer** [comment]
Yep, looks good
